nome = input ('Qual é o seu nome?')
print('Boas vindas', nome)
dia = input('Qual dia você nasceu?')
mes = input('Qual mês você nasceu?')
ano = input('Qual ano você nasceu?')
print('Que legal! Você nasceu no dia', dia,'no mês de', mes, 'no ano de', ano,'esta ficando velho')
primeiro = input('Primeiro número')
segundo = input('Segundo número')
soma = int(primeiro) + int(segundo)
print('A soma é', soma)
